In [1]:
import utils
import importlib
import os

importlib.reload(utils)
utils.set_gpu_ids([6])

[2023-09-12 15:00:22,415] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
os.environ["CUDA_VISIBLE_DEVICES"] = 6


# file

In [2]:
query_set_name = "prm800k-002validation-seed42"
queries_path = os.path.join(
    utils.project_root, "datasets", f"{query_set_name}-openai-queries.jsonl"
)
with open(queries_path, "r+") as f:
    print(len(f.readlines()))

1


# Path

In [4]:
from pathlib import Path

# 创建一个Path对象，表示当前目录
current_directory = Path.cwd()

# 使用glob方法查找所有以.py为扩展名的文件
python_files = current_directory.glob("*utils.py")

print(python_files)
print(list(python_files))
# 迭代生成器并输出匹配的文件的路径
for file_path in python_files:
    print(file_path)

<generator object Path.glob at 0x7f5a117c6810>
[PosixPath('/data/users/zhangjunlei/tyx/reward-by-prm800k/src/utils.py')]


# WandB

In [1]:
import wandb
import numpy as np

In [6]:
wandb.init(run_path="kidrain61/test/mpe5aes6", resume="must")

TypeError: init() got an unexpected keyword argument 'run_path'

In [24]:
metric_name = "roc_-1"

# 给定的 y_true 列表
y_true = [-1, 0, 1, 1, 1, 1]

# 生成三个类别的概率或分数
class_0_prob = [0.2, 0.6, 0.2, 0.1, 0.3, 0.6]
class_1_prob = [0.3, 0.4, 0.7, 0.4, 0.8, 0.9]
class_2_prob = [0.5, 0.2, 0.1, 0.4, 0.4, 0.2]

# 将这些概率或分数存储在一个嵌套的列表中
y_probas = [class_0_prob, class_1_prob, class_2_prob]

# 将嵌套列表转换为 NumPy 数组
y_probas = np.array(y_probas).transpose()

# 打印生成的 y_probas
print(y_probas)

[[0.2 0.3 0.5]
 [0.6 0.4 0.2]
 [0.2 0.7 0.1]
 [0.1 0.5 0.4]
 [0.3 0.8 0.4]
 [0.6 0.9 0.2]]


In [25]:
roc = wandb.plot.roc_curve(y_true, y_probas, title=metric_name.upper())
print(roc)

In [26]:
wandb.log({metric_name: roc})

In [4]:
utils.check_time_cost(["print(1)", "print(2)"])

1
4.410743713378906e-05 seconds to execute print(1)
2
1.430511474609375e-05 seconds to execute print(2)
7.319450378417969e-05 seconds to execute all codes


# Python

In [7]:
def foo():
    bar()


def bar():
    print(233)


foo()

233


In [2]:
exec("a = 1")
# print(a)

1


# NumPy

In [10]:
import numpy as np

In [15]:
cond = np.isin([1, 2, 3, 4, 5], [1, 2, 3])
print(cond)
chosen = np.where(cond)
print(chosen)

[ True  True  True False False]
(array([0, 1, 2]),)


# model

In [2]:
model_name_or_path = "/data/users/zhangjunlei/tyx/reward-by-prm800k/models/direct-prediction/meta-llama/Llama-2-7b-hf/step_100"

In [1]:
import torch

# 创建一个示例的 mask 张量
mask = torch.tensor([1, 1, 0, 1, 0], dtype=torch.bool)

# 将 mask 向左移动一位
shifted_mask = mask << 1

print(shifted_mask)

tensor([2, 2, 0, 2, 0])


In [7]:
# import transformers

# tokenizer = transformers.AutoTokenizer.from_pretrained(
#     "/data/users/zhangjunlei/tyx/.cache/huggingface/hub/models--hf-internal-testing--llama-tokenizer/snapshots/99eceeba6e8289bee767f0771166b5917e70e470"
# )

# print(tokenizer)
# print(tokenizer.pad_token_id)
# print(len(tokenizer.vocab))

tokenizer = utils.get_complete_tokenizer()
# print(tokenizer)
# print(tokenizer.pad_token_id)
# print(len(tokenizer.vocab))

head_tokens = <unk><s></s>
tokenizer.vocab_size = 32000
len(tokenizer.vocab) = 32000
tokenizer.special_tokens_map = {'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>'}
num_added_tokens = 1
head_tokens = <unk><s></s>
tokenizer.vocab_size = 32000
len(tokenizer.vocab) = 32001
tokenizer.special_tokens_map = {'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'pad_token': '<pad>'}
LlamaTokenizerFast(name_or_path='/data/users/zhangjunlei/tyx/.cache/huggingface/hub/models--hf-internal-testing--llama-tokenizer/snapshots/99eceeba6e8289bee767f0771166b5917e70e470', vocab_size=32000, model_max_length=4096, is_fast=True, padding_side='left', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'pad_token': '<pad>'}, clean_up_tokenization_spaces=False)


In [6]:
encoded_inputs = tokenizer("positive" * 768, return_tensors="pt")
print(encoded_inputs["input_ids"].shape)
tokenizer.prepare_for_model(encoded_inputs["input_ids"], return_tensors="pt")

torch.Size([1, 1536])


In [11]:
# utils.eval_model_with_best_of_n(model_name_or_path=model_name_or_path)

ZeRO-3 model weights detected at /data/users/zhangjunlei/tyx/reward-by-prm800k/models/direct-prediction/meta-llama/Llama-2-7b-hf/step_100.
ZeRO-3 model weights converted to HF model weights at /data/users/zhangjunlei/tyx/reward-by-prm800k/models/direct-prediction/meta-llama/Llama-2-7b-hf/step_100_fp16_hf
/data/users/zhangjunlei/tyx/reward-by-prm800k/eval/rated-samples/gpt-4-generatations/direct-prediction/meta-llama/Llama-2-7b-hf/step_100_fp16_hf/16-samples-per-problem.pkl exists.
Trial 1:
           majority_voting, [0.472, 0.564, 0.61, 0.646]
    positive_probs_product, [0.5, 0.542, 0.55, 0.554]
    positive_probs_minimum, [0.496, 0.528, 0.54, 0.536]
non_negative_probs_product, [0.498, 0.546, 0.542, 0.548]
non_negative_probs_minimum, [0.488, 0.534, 0.538, 0.544]
Trial 2:
           majority_voting, [0.476, 0.536, 0.61, 0.66]
    positive_probs_product, [0.512, 0.526, 0.538, 0.554]
    positive_probs_minimum, [0.514, 0.522, 0.528, 0.536]
non_negative_probs_product, [0.512, 0.526, 0.55

In [ ]:
# llama_config = transformers.LlamaConfig.from_pretrained(model_dirpath)

# llama_model = transformers.LlamaForCausalLM.from_pretrained(
#     pretrained_model_name_or_path=step_model_name_or_path,
#     config=llama_config,
#     device_map="auto",
#     low_cpu_mem_usage=True,
# )
# # 39.5s
# print(llama_model.config)

[2023-08-22 23:54:21,092] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
